### ISSUE TITLE
User-Accounts aus LDAP-Backend importieren

### ISSUE THREAD

**Issue by msteinhoff** [chaosdorf/chaospizza#10]
Dann kann man das ans chaosdorf-ldap anbinden und Leute müssen ihre Namen nicht wieder neu eingeben.

**Comment by feuerrot** [comment]
Won't happen: Selbst die Türsteuerung hängt nicht am LDAP und das ist 'n trusted host.

**Comment by feuerrot** [comment]
Zum Usermanagement für die Hosts, die auf vm.chaosdorf.de laufen.

**Comment by msteinhoff** [comment]
🤔

Sieht aus als brauchen wir noch eine Story damit man sich hier Accounts klicken kann.

**Comment by feuerrot** [comment]
Nimm halt Telegramaccounts? Es sieht ja bisher so aus, als wolltest du das eh eng daran binden.

**Comment by msteinhoff** [comment]
> Es sieht ja bisher so aus, als wolltest du das eh eng daran binden.

nope ich kehre nicht so wirklich welcher transport für notifications benutzt wird (wir könnten auch einen sprachsynthesizer fürs feldtelefon bauen) aber telegram scheint der beste weg um möglichst viele leute abzuholen :^)

**Comment by YtvwlD** [comment]
Was wäre denn mit [OpenID](https://openid.net/), [GitHub-OAuth](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/) oder [SPRESSO](https://spresso.me/)?

**Comment by msteinhoff** [comment]
@YtvwlD OpenID mit Twitter wäre wohl die einfachste Lösung.

Kann man ja das hier nehmen, das ist auch bei cookiecutter-django dabei (UND DAMIT MUSS ES JA GUT SEIN!!!1): https://github.com/uswaretech/Django-Socialauth

Twitter hat quasi jeder und wer nicht ist 1 Aluhut und hat eh kein Interesse daran die Software zu nutzen, aus Angst seine Essensbestellungen könnten getrackt werden.
